### ISSUE TITLE
[CSS/HTML] Multiple scroll bars

### ISSUE THREAD

**Issue by ebuildy** [wyukawa/yanagishima#10]
Not a big deal, but there are 3 vertical scroll bars:

![](http://b3.ms/aKb9L47b93RJ)

**Comment by wyukawa** [comment]
Thank you for reporting.

But I will release yanagishima v2 in a few weeks.
v2 UI will change dramatically.
Unfortunately, there is no backward compatibility.
So, it's difficult for me to handle this issue.

Sorry.
