### ISSUE TITLE
bug in PrestoServiceImpl.getPrestoQueryResult can made query error, Error Type is user cancel

### ISSUE THREAD

**Issue by weekey0** [wyukawa/yanagishima#11]
i fix it by this way,</br>
``` 
 Iterable<List<Object>>  tempData = null;
            while (client.isValid() ) {
                if(client.current().getNextUri() != null) {
                    client.advance();
                }else
                    break;
                if(client.current().getData()!=null)
                    tempData = client.current().getData();
            }
...
```
</br>
finnaly client.isValid() is false ,
and processData can't use client.current().getData() ,can use tempData

**Comment by wyukawa** [comment]
Could you please tell me how to reproduce a bug?

**Comment by weekey0** [comment]
it can be reproduce by insert data ,the status may be FINISHED or ERROR
![image](https://cloud.githubusercontent.com/assets/9337267/25215324/59635272-25cf-11e7-8685-b0f722212c1d.png)
![image](https://cloud.githubusercontent.com/assets/9337267/25215340/6d050e2e-25cf-11e7-93c1-f91e079d97b2.png)

**Comment by weekey0** [comment]
https://github.com/prestodb/presto/blob/c73359fe2173e01140b7d5f102b286e81c1ae4a8/presto-cli/src/main/java/com/facebook/presto/cli/Query.java

**Comment by wyukawa** [comment]
Sorry, I'm not sure.

If query error occurs, yanagishima shows error.
This is the spec.

What's your expected/actual result when query error occurs?

**Comment by weekey0** [comment]
Is likely to have been in the database, but there is a chance not to insert data

**Comment by weekey0** [comment]
In my test the result is the call interval 6s, call 604 times, the number of failed 548, finished the number of 56, should insert the data 604, the actual increase of data 592

**Comment by wyukawa** [comment]
Sorry, I can't understand what you mean.
