### ISSUE TITLE
The scheme list will not refresh while a scheme been selected

### ISSUE THREAD

**Issue by lloydsheng** [wyukawa/yanagishima#17]
**yanagishima version**: 4.0

**presto version**: 0.175

**Description of the problem including expected versus actual behavior**:
if a schema been selected , the schema list will not refresh while catalog changed.

**Steps to reproduce**:

![ezgif-2-8539a0cfe1](https://cloud.githubusercontent.com/assets/503040/26478470/10e80c80-41ff-11e7-9ec8-84bbf22aaafe.gif)

**Comment by wyukawa** [comment]
I can't reproduce.
Is there log(server or chrome developer console)?
I don't use redis and mongodb. It may be reason

**Comment by wyukawa** [comment]
please build master branch and check it out

**Comment by lloydsheng** [comment]
hi, i check out master branch code, build and run. the web page is blank and chrome console show this error
![image](https://cloud.githubusercontent.com/assets/503040/26517827/62adf8b6-42d3-11e7-84f6-e5202988da20.png)

**Comment by okazou** [comment]
@lloydsheng 
Hi, I thank you for report.
Try to remove localStorage, please.

**Comment by lloydsheng** [comment]
@okazou @wyukawa 
i've checked with master branch code. it's ok now.

**Comment by wyukawa** [comment]
😄
