### ISSUE TITLE
UI unable to detect catalog or schema or table!

### ISSUE THREAD

**Issue by iyerland** [wyukawa/yanagishima#18]
**yanagishima version**:

**presto version**: 0.170

**conf/yanagishima.properties**:

jetty.port=9000
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=datalake
presto.coordinator.server.datalake=http://ip-172-31-16-250.ec2.internal:8889
presto.redirect.server.datalake=http://ip-172-31-16-250.ec2.internal:8889
catalog.datalake=hive
schema.datalake=default
select.limit=500
audit.http.header.name=some.auth.header

**JVM version** (`java -version`): 
1.8.0

**Server OS version** (`uname -a` if on a Unix-like system):
Linux ip-172-31-16-250 4.4.35-33.55.amzn1.x86_64

**Client OS version**
4.0

**Browser**:
Chrome

**Description of the problem including expected versus actual behavior**:
The UI is not reading any catalogs/schema and hence unable to make any queries!

**Steps to reproduce**:

I have an AWS EMR setup with one Master & 1 Core with the following setup:
Presto: Presto 0.170 with Hadoop 2.7.3 HDFS and Hive 2.1.1 Metastore
Installed the UI on Master
Created table on Hive with links to JSON data on S3
Logged on to presto-cli and was able to do a simple select
Load UI and see if it is able to detect the default schema and tables

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
2017/05/31 12:58:49.451 +0000 INFO [YanagishimaServer] [Yanagishima] Loading yanagishima properties file
2017/05/31 12:58:50.134 +0000 INFO [log] [Yanagishima] Logging initialized @952ms
2017/05/31 12:58:50.290 +0000 INFO [YanagishimaServer] [Yanagishima] Yanagishima Server started...
2017/05/31 12:58:50.292 +0000 INFO [Server] [Yanagishima] jetty-9.3.13.M0
2017/05/31 12:58:50.724 +0000 INFO [ContextHandler] [Yanagishima] Started o.e.j.s.ServletContextHandler@5e7cd6cc{/,file:///home/hadoop/yanagishima-4.0/web/,AVAILABLE}
2017/05/31 12:58:50.733 +0000 INFO [ServerConnector] [Yanagishima] Started ServerConnector@7b4c50bc{HTTP/1.1,[http/1.1]}{0.0.0.0:9000}
2017/05/31 12:58:50.733 +0000 INFO [Server] [Yanagishima] Started @1552ms
2017/05/31 12:58:50.733 +0000 INFO [YanagishimaServer] [Yanagishima] Yanagishima Server running port 9000.
2017/05/31 12:59:03.886 +0000 ERROR [PrestoServlet] [Yanagishima] No value present
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at yanagishima.config.YanagishimaConfig.getPrestoCoordinatorServer(YanagishimaConfig.java:17)
	at yanagishima.service.PrestoServiceImpl.getStatementClient(PrestoServiceImpl.java:268)
	at yanagishima.service.PrestoServiceImpl.doQuery(PrestoServiceImpl.java:97)
	at yanagishima.servlet.PrestoServlet.lambda$doPost$4(PrestoServlet.java:96)
	at java.util.Optional.ifPresent(Optional.java:159)
	at yanagishima.servlet.PrestoServlet.doPost(PrestoServlet.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)	

**Provide screenshots (if relevant)**:
<img width="1396" alt="yanagishima_on_chrome" src="https://cloud.githubusercontent.com/assets/896628/26633509/a884a46e-45e1-11e7-9afe-83526ee95633.png">

**Comment by iyerland** [comment]
Here's what I understood about the properties file:

`presto.datasources=datalake`
This is to allocate a name to the datasource. This can be any name, it could also have been called `foo`!! Doesn't matter, as long as we continue to use this datasource name subsequently?! Am I right? I just randomly called it `datalake`!

Here's a line from  presto `config.properties` file:
`discovery.uri=http://ip-172-31-16-250.ec2.internal:8889`
So, this is the hostname:port where presto server is running locally (on same host). I could have kept hostname as `localhost`, it would be the same.

But, I don't understand what you mean by `Is presto.coordinator.server.datalake really set?`??

**Comment by wyukawa** [comment]
You are right.

datasource name can be any name.

But, if ```presto.coordinator.server.datalake``` is not set, exception can be thrown.

https://github.com/wyukawa/yanagishima/blob/master/src/main/java/yanagishima/config/YanagishimaConfig.java#L17

So, ```presto.coordinator.server.datalake``` seems not to be set.

**Comment by iyerland** [comment]
OK. Found out the problem :)

I had to modify the security groups of my EMR Master to allow port 8889 ... see attached screenshot!

Sorry about that ... and thanks!

<img width="892" alt="screen shot 2017-05-31 at 10 50 12 am" src="https://cloud.githubusercontent.com/assets/896628/26638005/050451c8-45ef-11e7-8b22-9e7a2a6ceffb.png">
