### ISSUE TITLE
yanagishima JVM process eats lots of virtual memory

### ISSUE THREAD

**Issue by ogibayashi** [wyukawa/yanagishima#3]
One day our yanagishima process crashed because of insufficient memory.

Here is the last part of y.log. (standard output of yanagishima process)

```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool::allocate
# An error report file with more information is saved as:
# /home/user1/yanagishima-0.0.9/hs_err_pid98805.log
```

I checked sar log under /var/log/sa and "kbcommit" went down about 32GB at the time yanagishima process died. This means yanagishima used this size of virtual memory.

```
12:00:01 AM kbmemfree kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit
...
12:21:01 PM  22745608  10116924     30.79    316052   2414628  35039220     94.56
12:22:01 PM  22746684  10115848     30.78    316052   2414672  35103912     94.73
12:23:01 PM  26228032   6634500     20.19    316056   2422864    652408      1.76
12:24:01 PM  26229060   6633472     20.19    316056   2422892    654596      1.77
```

Actually, 10 hours after I restarted yanagishima process, it already takes about 17GB VSZ. (-Xmx is just 3GB by the way)

```
$ ps -eo pid,vsz,rss,cmd | grep yanagishima
139080 17523888 908436 java -Xmx3G -cp :bin/../lib/annotations-2.0.3.jar:bin/../lib/antlr4-runtime-4.5.1.jar:bin/../ ....
```

If I check hs_err_pid98805.log, there are lots of "http-client-anonymous" threads.

```
Java Threads: ( => current thread )
  0x00007f5f92203000 JavaThread "http-client-anonymous3611-scheduler-41356" daemon [_thread_blocked, id=138452, stack(0x00007f5f40304000,0x00007f5f40405000)]
  0x00007f5f921aa000 JavaThread "http-client-anonymous3611-41355" daemon [_thread_blocked, id=138451, stack(0x00007f5f40405000,0x00007f5f40506000)]
  0x00007f5f921a8000 JavaThread "http-client-anonymous3611-41354" daemon [_thread_blocked, id=138450, stack(0x00007f5f40506000,0x00007f5f40607000)]
  0x00007f5f921a6000 JavaThread "http-client-anonymous3611-41353" daemon [_thread_blocked, id=138449, stack(0x00007f5f40607000,0x00007f5f40708000)]
```

There were 32530 threads and 32499 threads were "http-client-anonymous".

```
$ grep JavaThread ~/yanagishima-0.0.9/hs_err_pid98805.log  | wc -l
32530

$ grep JavaThread ~/yanagishima-0.0.9/hs_err_pid98805.log  | grep http-client-anonymous | wc -l
32499
```

It seems that yanagishima creates huge number of threads, so the total amount of thread stack becomes GBs of memory.

I have not found the root cause yet, but these "http-client-anonymous" seems to be created in JettyHttpClient in airlift http-client. So are there any problem with the usage of that library?

**Comment by wyukawa** [comment]
Thank you for issuing.

I check presto-cli and I confirm that yanagishima needs to close JettyHttpClient.

If I add JettyHttpClient#close, I confirm that number of threads decrease as the following.

ps -L <pid> | wc -l
5869

↓

ps -L <pid> | wc -l
80

So, I believe that this fix resolve the issue.

**Comment by wyukawa** [comment]
I notice that that number of threads still increase.

I implement the yanaghishima by reference to the presto-cli, so I re-confirm presto-cli implementation.

As result, I understand that to close JettyHttpClient is meaningless and JettyHttpClient should to be reused to avoid to create QueuedThreadPool every request.
