### ISSUE TITLE
hi,I want to use nginx for redirect ,how 

### ISSUE THREAD

**Issue by jack161641** [wyukawa/yanagishima#8]
I use nginx for reverse proxy ,nginx config is     

server {
    listen       80;
    server_name  localhost;
    include /etc/nginx/default.d/*.conf; 
}
location /presto-ui  {
    proxy_pass http://10.214.2.82:8889;
}
yanagishima.properties config is
jetty.port=8889
presto.coordinator.server=http://master:8888
presto.redirect.server=http://10.214.0.96/presto-ui
catalog=hive
schema=default
select.limit=500

but,I access get error,these is not css, image,etc,only have text in index.html,like can't  found web base directory
how config use reverse proxy?

**Comment by wyukawa** [comment]
Hmm, I'm not familiar with Nginx.
Please contact to Nginx Maling List.

**Comment by jack161641** [comment]
We fix it by rewrite original code ,Thanks
