### ISSUE TITLE
[Javascript] Cannot read property 'totalDrivers' of undefined

### ISSUE THREAD

**Issue by ebuildy** [wyukawa/yanagishima#9]
Hello, first of all thanks you for this awesome project, it just works! (using it with presto 0.161),

A javascript error:

```
Uncaught TypeError: Cannot read property 'totalDrivers' of undefined
    at Array.<anonymous> (yanagishima.js:993)
    at Array._a.data (d3.min.js:3)
    at renderDoneQueries (yanagishima.js:992)
    at yanagishima.js:846
    at d3.min.js:1
    at Object.<anonymous> (d3.min.js:1)
    at Object.t (d3.min.js:1)
    at XMLHttpRequest.u (d3.min.js:1)
```

**Comment by wyukawa** [comment]
Thank you for reporting.

But I'm using presto 0.170 and I can't reproduce the error.
And I will release yanagishima v2 in a few weeks.
v2 UI will change dramatically.
Unfortunately, there is no backward compatibility.
So, it's difficult for me to handle this issue.

Sorry.
